/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tienda;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnodaw
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        iniciarModelos();
    }
    public Inicio(String nombre) {
        initComponents();
        jTextFieldBienvenido.setText("Bienvenido " + nombre);
        iniciarModelos();
               
        
    }
    
    private void iniciarModelos(){
         modeloBebidas = new DefaultComboBoxModel();
        modeloPizzas = new DefaultComboBoxModel();
        modeloPizzas.addElement("Carbonara");
        modeloPizzas.addElement("Margarita");
        modeloPizzas.addElement("Barbacoa");
        modeloBebidas.addElement("Agua");
        modeloBebidas.addElement("Nestea");
        modeloBebidas.addElement("Cocacola");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBienvenido = new javax.swing.JTextField();
        jComboBoxMasas = new javax.swing.JComboBox<>();
        jButtonEncargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaListadoPedidos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEspecias = new javax.swing.JComboBox<>();
        jTextFieldAñadirProducto = new javax.swing.JTextField();
        jButtonBotonAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldBienvenido.setEditable(false);
        jTextFieldBienvenido.setText("           BIENVENIDO USUARIO");

        jComboBoxMasas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto", "Bebida", "Pizza" }));
        jComboBoxMasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMasasActionPerformed(evt);
            }
        });

        jButtonEncargar.setText("ENCARGAR");
        jButtonEncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEncargarMouseClicked(evt);
            }
        });

        jTextAreaListadoPedidos.setColumns(20);
        jTextAreaListadoPedidos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaListadoPedidos);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tienda/pizzalogo.jpg"))); // NOI18N

        jComboBoxEspecias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona" }));
        jComboBoxEspecias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEspeciasActionPerformed(evt);
            }
        });

        jTextFieldAñadirProducto.setText("Añade un nuevo producto");

        jButtonBotonAñadir.setText("AÑADIR");
        jButtonBotonAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBotonAñadirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxMasas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxEspecias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldAñadirProducto))
                    .addComponent(jButtonBotonAñadir))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(275, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(jTextFieldBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jTextFieldBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jComboBoxEspecias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jTextFieldAñadirProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBotonAñadir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButtonEncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEncargarMouseClicked
        // TODO add your handling code here:
        String producto,pedido;
        
        producto = (String) jComboBoxMasas.getSelectedItem();
        pedido = (String) jComboBoxEspecias.getSelectedItem();
        
        
        
        jTextAreaListadoPedidos.setText(jTextAreaListadoPedidos.getText() +  "\n" + producto + " " + pedido);
    }//GEN-LAST:event_jButtonEncargarMouseClicked

    private void jComboBoxMasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMasasActionPerformed
        // TODO add your handling code here:
        int opc;
        
        opc = jComboBoxMasas.getSelectedIndex();
        switch (opc){
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Selecciona un Producto","",2);
                break;
            case 1:
                jComboBoxEspecias.setModel(modeloBebidas);
                break;
            case 2:
                jComboBoxEspecias.setModel(modeloPizzas);
                break;
        }
    }//GEN-LAST:event_jComboBoxMasasActionPerformed

    private void jComboBoxEspeciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEspeciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEspeciasActionPerformed

    private void jButtonBotonAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBotonAñadirMouseClicked
        // TODO add your handling code here:
        String newproduct = jTextAreaListadoPedidos.getText();
        
        jComboBoxMasas.addItem(newproduct);
        
    }//GEN-LAST:event_jButtonBotonAñadirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    private javax.swing.DefaultComboBoxModel<String> modeloBebidas;
    private javax.swing.DefaultComboBoxModel<String> modeloPizzas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBotonAñadir;
    private javax.swing.JButton jButtonEncargar;
    private javax.swing.JComboBox<String> jComboBoxEspecias;
    private javax.swing.JComboBox<String> jComboBoxMasas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaListadoPedidos;
    private javax.swing.JTextField jTextFieldAñadirProducto;
    private javax.swing.JTextField jTextFieldBienvenido;
    // End of variables declaration//GEN-END:variables
}
